// AeroSpark Constants & Configuration

export const SITE_CONFIG = {
  name: "AeroSpark",
  tagline: "Aerospace Learning Ecosystem",
  description:
    "A futuristic aerospace engineering ecosystem combining education, R&D, and enterprise solutions.",
  url: "https://aerospark.io",
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Academy", href: "/academy" },
  { label: "Consultation", href: "/consultation" },
  { label: "Insights", href: "/insights" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const COURSES = [
  {
    id: "dgca-drone-regulations",
    title: "DGCA Drone Regulations",
    category: "Compliance & Regulations",
    description:
      "Practical introduction to UAS (Drones) rules, compliance requirements, and safe operating practices in India. Covers DGCA, MoCA, and DigitalSky awareness.",
    duration: "6 weeks",
    lessons: 24,
    level: "Beginner" as const,
    price: 1499,
    rating: 4.9,
    students: 1240,
    image: "/courses/drone-rules.jpg",
    tags: ["DGCA", "UAS", "Compliance", "India"],
    topics: [
      "Introduction to UAS regulations in India",
      "DGCA, MoCA, and DigitalSky overview",
      "Drone categories and operational limitations",
      "Registration and compliance awareness",
      "Remote pilot responsibilities",
      "Airspace, permissions, and safe flight planning",
      "Documentation and operational discipline",
      "Common compliance mistakes and safety risks",
    ],
    eligibility: "Students, aspiring drone pilots, entrepreneurs, and professionals from photography, surveying, agriculture, and inspection fields.",
    outcome: "Clear foundation in Indian UAS regulations and basic requirements for safe, responsible, and compliant drone operations.",
  },
  {
    id: "faa-drone-regulations",
    title: "FAA Drone Regulations",
    category: "Compliance & Regulations",
    description:
      "Introduction to UAS rules and safe operating practices under the FAA framework in the United States. Covers Part 107, Remote ID, and airspace authorization.",
    duration: "6 weeks",
    lessons: 22,
    level: "Beginner" as const,
    price: 1999,
    rating: 4.8,
    students: 890,
    image: "/courses/faa-drone.jpg",
    tags: ["FAA", "Part 107", "UAS", "USA"],
    topics: [
      "Introduction to UAS regulations in the United States",
      "FAA framework and operator responsibilities",
      "Recreational vs commercial drone operations",
      "FAA Part 107 awareness",
      "Registration and Remote ID basics",
      "Airspace awareness and flight authorization overview",
      "Safe operating practices",
      "Risk, liability, and common operational mistakes",
    ],
    eligibility: "Beginners interested in UAS operations in the USA, aspiring FAA remote pilots, drone business owners, and professionals using drones commercially.",
    outcome: "Basic understanding of FAA UAS compliance and safe flight practices for responsible drone operations in the United States.",
  },
  {
    id: "easa-drone-regulations",
    title: "EASA Drone Regulations",
    category: "Compliance & Regulations",
    description:
      "Overview of UAS rules and compliance under the European aviation safety framework. Covers Open, Specific, and Certified category awareness with NAA roles.",
    duration: "6 weeks",
    lessons: 20,
    level: "Beginner" as const,
    price: 1999,
    rating: 4.7,
    students: 620,
    image: "/courses/easa-drone.jpg",
    tags: ["EASA", "Europe", "UAS", "Compliance"],
    topics: [
      "Introduction to UAS regulations in Europe",
      "EASA and National Aviation Authority overview",
      "Open, Specific, and Certified category awareness",
      "Operator registration and pilot responsibility",
      "Airspace and geographical zone awareness",
      "Equipment and operational compliance basics",
      "Safe operating practices",
      "Risk, privacy, and common compliance mistakes",
    ],
    eligibility: "Beginners interested in UAS operations in Europe, aspiring remote pilots, drone service providers, and professionals from photography, surveying, and inspection.",
    outcome: "Clear foundation in EASA UAS rules and basic compliance approach for safe drone operations in Europe.",
  },
  {
    id: "aerospace-fundamentals",
    title: "Aerospace Engineering Fundamentals",
    category: "Technical Foundation",
    description:
      "Foundation in aerospace engineering concepts including aircraft basics, flight principles, structures, propulsion, materials, and industry applications.",
    duration: "6 weeks",
    lessons: 28,
    level: "Beginner" as const,
    price: 1499,
    rating: 4.9,
    students: 2100,
    image: "/courses/aerospace-fundamentals.jpg",
    tags: ["Aerospace", "Aviation", "Engineering", "Fundamentals"],
    topics: [
      "Introduction to aerospace engineering",
      "Aircraft, spacecraft, and UAS overview",
      "Basic flight principles",
      "Aircraft structures and materials awareness",
      "Propulsion system basics",
      "Flight control and stability awareness",
      "Introduction to avionics and aircraft systems",
      "Aerospace manufacturing and quality awareness",
      "Industry applications and career pathways",
      "Emerging trends in aerospace and drone technology",
    ],
    eligibility: "Students interested in aerospace or aeronautical engineering, beginners exploring aviation or drone technology, and professionals seeking aerospace domain awareness.",
    outcome: "Clear understanding of aerospace engineering fundamentals and ability to identify major aerospace systems, basic flight concepts, and engineering applications.",
  },
  {
    id: "aerodynamics",
    title: "Aerodynamics",
    category: "Technical Foundation",
    description:
      "Foundation in aerodynamics with focus on airflow behavior, lift, drag, pressure, stability, and performance concepts for aircraft, drones, and wings.",
    duration: "6 weeks",
    lessons: 26,
    level: "Beginner" as const,
    price: 1999,
    rating: 4.9,
    students: 1580,
    image: "/courses/aerodynamics.jpg",
    tags: ["Aerodynamics", "Airfoil", "Lift", "Drag"],
    topics: [
      "Introduction to aerodynamics",
      "Airflow, pressure, velocity, and forces",
      "Lift, drag, thrust, and weight concepts",
      "Airfoil and wing basics",
      "Angle of attack and stall awareness",
      "Basic aircraft stability and control awareness",
      "Propeller and rotor aerodynamic awareness",
      "Aerodynamics in drones, aircraft, and vehicles",
      "Introduction to performance improvement concepts",
      "Connection between aerodynamics, CFD, and design validation",
    ],
    eligibility: "Aerospace, aeronautical, and mechanical engineering students, UAS and aviation learners, CAD/FEA/CFD learners seeking aerodynamic understanding.",
    outcome: "Clear foundation in aerodynamic principles and understanding of how airflow affects design, stability, performance, and efficiency in aircraft and drones.",
  },
  {
    id: "drone-components",
    title: "Drone Components & Applications",
    category: "Technical Foundation",
    description:
      "Foundation in UAS technology covering major drone components, basic aerodynamics, industry applications, and R&D awareness for practical drone solutions.",
    duration: "8 weeks",
    lessons: 32,
    level: "Beginner" as const,
    price: 2499,
    rating: 4.8,
    students: 1120,
    image: "/courses/drone-components.jpg",
    tags: ["UAS", "Drone", "Components", "R&D"],
    topics: [
      "UAS terminology and basic concepts",
      "Major drone components and system overview",
      "Basic aerodynamics and flight principles",
      "Drone types, configurations, and use cases",
      "Payload, sensor, battery, propulsion, and control system awareness",
      "Industry applications of drones",
      "Introduction to drone R&D and innovation process",
      "Concept-to-prototype awareness",
      "Component selection and payload integration basics",
      "Testing, validation, and performance improvement awareness",
    ],
    eligibility: "Students and beginners interested in drone technology, aspiring drone pilots, entrepreneurs exploring drone-based ideas, professionals from agriculture, surveying, and inspection.",
    outcome: "Clear understanding of UAS components, applications, terminology, basic aerodynamics, and R&D basics with awareness of how drone ideas move toward practical solutions.",
  },
  {
    id: "matlab-programming",
    title: "MATLAB Programming",
    category: "Technical Foundation",
    description:
      "Foundation in MATLAB programming for engineering, data analysis, mathematical modeling, and technical problem-solving in aerospace and simulation applications.",
    duration: "6 weeks",
    lessons: 24,
    level: "Beginner" as const,
    price: 2499,
    rating: 4.7,
    students: 750,
    image: "/courses/matlab.jpg",
    tags: ["MATLAB", "Programming", "Engineering", "Data"],
    topics: [
      "Introduction to MATLAB environment",
      "Basic programming concepts",
      "Variables, arrays, matrices, and functions",
      "Mathematical operations and plotting",
      "Data handling and visualization basics",
      "Engineering problem-solving using MATLAB",
      "Introduction to scripts and functions",
      "Basic simulation and modeling awareness",
      "Applications in aerospace, drones, and engineering analysis",
    ],
    eligibility: "Engineering students and graduates, aerospace, mechanical, electrical learners, and professionals who want to improve engineering computation skills.",
    outcome: "Clear foundation in MATLAB programming for basic engineering calculations, data visualization, problem-solving, and technical project support.",
  },
  {
    id: "catia-design",
    title: "CATIA Design",
    category: "Design Foundation",
    description:
      "Practical foundation in 3D design using CATIA with an aircraft-oriented approach. Covers part modeling, assembly basics, drafting, and professional CAD workflow.",
    duration: "10 weeks",
    lessons: 40,
    level: "Intermediate" as const,
    price: 3999,
    rating: 4.9,
    students: 1580,
    image: "/courses/catia-design.jpg",
    tags: ["CATIA", "CAD", "Aircraft", "3D Design"],
    topics: [
      "Introduction to CATIA and CAD design workflow",
      "Basic sketching and part design concepts",
      "Aircraft-oriented component design awareness",
      "General mechanical and product design approach",
      "3D modeling, constraints, features, and design intent",
      "Assembly design basics",
      "Drafting and drawing generation awareness",
      "Design modification and error correction basics",
      "Introduction to manufacturability and design documentation",
      "Professional CAD practices and file management awareness",
    ],
    eligibility: "Students and beginners in CAD design, mechanical, aerospace, aeronautical learners, UAS and aircraft design enthusiasts, and engineering graduates.",
    outcome: "Foundation in CATIA-based design — create basic 3D parts, understand assembly structure, read design intent, and apply CAD concepts to aircraft and product design.",
  },
  {
    id: "nx-cad-design",
    title: "NX CAD Design",
    category: "Design Foundation",
    description:
      "Practical foundation in 3D design using Siemens NX CAD with aircraft-oriented and general product design approach. Covers part modeling, assembly, and drafting.",
    duration: "10 weeks",
    lessons: 38,
    level: "Intermediate" as const,
    price: 3999,
    rating: 4.8,
    students: 920,
    image: "/courses/nx-cad.jpg",
    tags: ["NX CAD", "Siemens", "CAD", "3D Modeling"],
    topics: [
      "Introduction to NX CAD and design workflow",
      "Basic sketching and feature-based modeling",
      "Aircraft-oriented component design awareness",
      "General mechanical and product design approach",
      "3D part modeling and design modification basics",
      "Assembly design fundamentals",
      "Drafting and technical drawing awareness",
      "Design validation and model review basics",
      "Introduction to manufacturability and documentation",
      "Professional CAD practices and organized design workflow",
    ],
    eligibility: "Students and beginners in NX CAD, mechanical, aerospace, aeronautical learners, UAS and aircraft enthusiasts, and professionals strengthening CAD skills.",
    outcome: "Foundation in NX CAD-based design — create basic 3D models, understand assembly concepts, apply design modifications for aircraft and product design.",
  },
  {
    id: "mathematics-fea-cfd",
    title: "Mathematics for FEA & CFD",
    category: "Engineering Mathematics",
    description:
      "Essential mathematical foundation for understanding Finite Element Analysis and Computational Fluid Dynamics — vectors, matrices, calculus, and numerical methods.",
    duration: "6 weeks",
    lessons: 24,
    level: "Intermediate" as const,
    price: 2499,
    rating: 4.7,
    students: 540,
    image: "/courses/math-fea-cfd.jpg",
    tags: ["Mathematics", "FEA", "CFD", "Simulation"],
    topics: [
      "Engineering mathematics overview for simulation",
      "Vectors, matrices, and basic field concepts",
      "Calculus and differential equation awareness",
      "Stress, strain, load, displacement, pressure, velocity, and flow variables",
      "Boundary conditions and constraints",
      "Numerical methods and approximation awareness",
      "Meshing, discretization, error, and convergence basics",
      "Mathematical understanding of structural and fluid behavior",
      "Application of mathematics in FEA and CFD result interpretation",
    ],
    eligibility: "Engineering students and graduates, CAD learners moving toward simulation, mechanical, aerospace, civil, and automotive engineering learners.",
    outcome: "Clear foundation in the mathematical concepts behind FEA and CFD — prepared to understand simulation workflows, structural analysis, and result interpretation.",
  },
  {
    id: "fea-analysis",
    title: "FEA Analysis",
    category: "Simulation & Analysis",
    description:
      "Foundation in Finite Element Analysis for engineering design and product validation. Study structural behavior, stress, deformation, and design improvement in aerospace products.",
    duration: "10 weeks",
    lessons: 38,
    level: "Advanced" as const,
    price: 4499,
    rating: 4.8,
    students: 680,
    image: "/courses/fea.jpg",
    tags: ["FEA", "Structural", "Simulation", "CAE"],
    topics: [
      "Introduction to FEA and CAE workflow",
      "Basic concepts of stress, strain, load, and deformation",
      "Geometry preparation and model simplification awareness",
      "Material properties and boundary condition basics",
      "Meshing concepts and result interpretation",
      "Structural analysis awareness",
      "Design validation and improvement approach",
      "Common errors and best practices in FEA",
      "Applications in aircraft, drones, and general product design",
    ],
    eligibility: "Engineering students and graduates, mechanical, aerospace, aeronautical learners, CAD designers moving toward simulation, UAS and aircraft enthusiasts.",
    outcome: "Clear foundation in FEA concepts and simulation workflow — understand how structural analysis supports design decisions, product improvement, and engineering validation.",
  },
  {
    id: "cfd-analysis",
    title: "CFD Analysis",
    category: "Simulation & Analysis",
    description:
      "Foundation in Computational Fluid Dynamics for understanding airflow, fluid behavior, and aerodynamic performance in aircraft, drones, and engineering applications.",
    duration: "10 weeks",
    lessons: 40,
    level: "Advanced" as const,
    price: 4999,
    rating: 4.9,
    students: 720,
    image: "/courses/cfd.jpg",
    tags: ["CFD", "Aerodynamics", "Simulation", "Fluids"],
    topics: [
      "Introduction to CFD and simulation workflow",
      "Basic fluid flow and aerodynamic concepts",
      "Geometry preparation and domain awareness",
      "Boundary conditions and material setup basics",
      "Meshing concepts for CFD",
      "Airflow, pressure, velocity, and turbulence awareness",
      "Result interpretation and performance understanding",
      "Common CFD errors and best practices",
      "Applications in aircraft, drones, and general engineering systems",
    ],
    eligibility: "Engineering students and graduates, mechanical, aerospace, aeronautical learners, CAD designers moving toward fluid simulation, and performance analysis professionals.",
    outcome: "Clear foundation in CFD concepts and simulation workflow — understand how fluid analysis supports aerodynamic study, design improvement, and performance-based decisions.",
  },
  {
    id: "as9100d-quality",
    title: "AS9100D Quality Management",
    category: "Quality & Industry Standards",
    description:
      "Practical foundation in aerospace quality management with AS9100D awareness. Covers quality policy, documentation, traceability, risk management, and continual improvement.",
    duration: "8 weeks",
    lessons: 36,
    level: "Intermediate" as const,
    price: 2999,
    rating: 4.7,
    students: 650,
    image: "/courses/as9100d.jpg",
    tags: ["AS9100D", "Quality", "Aerospace", "Compliance"],
    topics: [
      "Introduction to quality management in aerospace and UAS industries",
      "Overview of AS9100D and aerospace quality standards",
      "Basic understanding of ISO 9001 and AS9100D relationship",
      "Quality policy, objectives, and process-based thinking",
      "Documentation, records, and traceability awareness",
      "Risk-based thinking and operational risk awareness",
      "Product safety, conformity, and reliability concepts",
      "Supplier quality and purchase control awareness",
      "Inspection, verification, and nonconformity basics",
      "Corrective action and continual improvement awareness",
      "Audit readiness and compliance mindset",
      "Role of quality culture in aerospace and drone industries",
    ],
    eligibility: "Students and beginners in aerospace quality, UAS, aviation, and aerospace technology learners, quality and production professionals, and entrepreneurs with drone/aerospace products.",
    outcome: "Clear foundation in aerospace quality management and AS9100D awareness — understand quality terms, documentation, traceability, compliance mindset, and continual improvement.",
  },
];

export const COURSE_BUNDLES = [
  {
    id: "drone-regulations-bundle",
    title: "Drone Regulations Bundle",
    description: "Complete global drone regulations coverage — India, USA & Europe",
    includes: ["DGCA Drone Regulations", "FAA Drone Regulations", "EASA Drone Regulations"],
    courseIds: ["dgca-drone-regulations", "faa-drone-regulations", "easa-drone-regulations"],
    price: 4499,
    savings: 999,
    color: "blue",
  },
  {
    id: "technical-foundation-bundle",
    title: "Technical Foundation Bundle",
    description: "Complete technical foundation for aerospace and drone engineering",
    includes: ["Aerospace Engineering Fundamentals", "Aerodynamics", "Drone Components & Applications", "MATLAB Programming"],
    courseIds: ["aerospace-fundamentals", "aerodynamics", "drone-components", "matlab-programming"],
    price: 7499,
    savings: 1497,
    color: "green",
  },
  {
    id: "design-bundle",
    title: "Design Bundle",
    description: "Master both industry-standard 3D CAD platforms",
    includes: ["CATIA Design", "NX CAD Design"],
    courseIds: ["catia-design", "nx-cad-design"],
    price: 6999,
    savings: 999,
    color: "purple",
  },
  {
    id: "simulation-bundle",
    title: "Simulation Bundle",
    description: "Complete simulation and analysis pathway from math to FEA & CFD",
    includes: ["Mathematics for FEA & CFD", "FEA Analysis", "CFD Analysis"],
    courseIds: ["mathematics-fea-cfd", "fea-analysis", "cfd-analysis"],
    price: 9999,
    savings: 1998,
    color: "orange",
  },
  {
    id: "complete-program",
    title: "Complete Aerospace, Drone & Simulation Program",
    description: "All 13 courses — the ultimate aerospace learning journey",
    includes: ["All 13 courses included"],
    courseIds: [],
    price: 24999,
    savings: 8497,
    color: "red",
  },
];

export const LEARNER_BENEFITS = [
  "Live interactive classes",
  "One-on-one mentorship support",
  "Dedicated doubt-solving sessions",
  "Structured learning materials and resources based on course requirements",
  "Practical examples and industry-oriented explanations",
  "Guided preparation for assessments",
  "Result-based course completion certificate",
  "Support for higher-level learning, projects, and professional skill development",
];

export const CONSULTATION_SERVICES = [
  {
    id: "uas-certification",
    title: "UAS Type Certification",
    description:
      "End-to-end DGCA type certification support for UAS manufacturers — from documentation to flight testing.",
    icon: "Shield",
    features: [
      "DGCA compliance roadmap",
      "Design review & documentation",
      "Test planning & execution",
      "Certification submission support",
    ],
  },
  {
    id: "as9100d-quality",
    title: "AS9100D Quality Systems",
    description:
      "Implement and maintain aerospace quality management systems for global supply chain participation.",
    icon: "Award",
    features: [
      "Gap analysis & readiness audit",
      "QMS documentation support",
      "Internal audit training",
      "Certification body preparation",
    ],
  },
  {
    id: "drone-rd",
    title: "Drone R&D Consulting",
    description:
      "Technical consulting for drone design, development, and testing — from concept to production.",
    icon: "Cpu",
    features: [
      "Concept design & feasibility",
      "Prototype development",
      "Flight testing & validation",
      "Production transition support",
    ],
  },
  {
    id: "design-simulation",
    title: "Design & Simulation",
    description:
      "Advanced CAD/CAE consulting for aerospace structures, mechanisms, and system-level simulation.",
    icon: "Box",
    features: [
      "3D modeling & surfacing",
      "FEA/CFD analysis",
      "Design optimization",
      "Digital twin development",
    ],
  },
  {
    id: "procurement",
    title: "Aerospace Procurement",
    description:
      "Strategic procurement consulting for aerospace-grade materials, components, and vendor management.",
    icon: "Package",
    features: [
      "Vendor qualification",
      "Material sourcing",
      "Supply chain optimization",
      "Cost reduction strategies",
    ],
  },
];

export const BLOG_POSTS = [
  {
    id: "future-of-uas",
    title: "The Future of UAS in India: DGCA's Evolving Framework",
    excerpt:
      "An in-depth analysis of India's drone regulatory landscape and upcoming policy changes that will reshape the industry.",
    category: "Regulatory",
    author: "Dr. Arun Mehta",
    date: "2026-05-01",
    readTime: "8 min",
    image: "/blog/uas-future.jpg",
  },
  {
    id: "composite-materials",
    title: "Advanced Composite Materials in Modern Aerospace",
    excerpt:
      "How carbon fiber and advanced composites are revolutionizing aircraft design, reducing weight, and improving performance.",
    category: "Engineering",
    author: "Priya Sharma",
    date: "2026-04-25",
    readTime: "12 min",
    image: "/blog/composites.jpg",
  },
  {
    id: "ai-in-aerospace",
    title: "AI-Driven Quality Inspection in Aerospace Manufacturing",
    excerpt:
      "Machine learning applications in non-destructive testing, automated visual inspection, and predictive maintenance.",
    category: "Technology",
    author: "Vikram Rao",
    date: "2026-04-18",
    readTime: "10 min",
    image: "/blog/ai-aerospace.jpg",
  },
  {
    id: "digital-twin",
    title: "Digital Twins: Transforming Aerospace Product Lifecycle",
    excerpt:
      "How digital twin technology is bridging the gap between design simulation and real-world aerospace operations.",
    category: "Technology",
    author: "Dr. Arun Mehta",
    date: "2026-04-10",
    readTime: "9 min",
    image: "/blog/digital-twin.jpg",
  },
  {
    id: "evtol-revolution",
    title: "eVTOL Revolution: Urban Air Mobility Takes Flight",
    excerpt:
      "The engineering challenges and market opportunities in the rapidly evolving electric vertical takeoff and landing sector.",
    category: "Industry",
    author: "Priya Sharma",
    date: "2026-04-02",
    readTime: "11 min",
    image: "/blog/evtol.jpg",
  },
  {
    id: "additive-manufacturing",
    title: "Additive Manufacturing in Aerospace: Beyond Prototyping",
    excerpt:
      "3D printing for flight-critical components — certifications, materials, and production-scale applications.",
    category: "Manufacturing",
    author: "Vikram Rao",
    date: "2026-03-28",
    readTime: "7 min",
    image: "/blog/additive.jpg",
  },
];

export const STATS = [
  { label: "Students Trained", value: "8,200+", icon: "Users" },
  { label: "Courses Available", value: "24", icon: "BookOpen" },
  { label: "Industry Partners", value: "50+", icon: "Building" },
  { label: "Certifications Issued", value: "3,600+", icon: "Award" },
];

export const TESTIMONIALS = [
  {
    name: "Rajesh Kumar",
    role: "Drone Startup Founder",
    content:
      "AeroSpark's drone certification course gave me the exact knowledge I needed to navigate DGCA regulations. Our startup got type-certified in record time.",
    avatar: "/avatars/rajesh.jpg",
    rating: 5,
  },
  {
    name: "Sneha Patel",
    role: "Quality Engineer, HAL",
    content:
      "The AS9100D course is incredibly thorough. It directly helped me implement quality systems at our facility and pass the certification audit on the first attempt.",
    avatar: "/avatars/sneha.jpg",
    rating: 5,
  },
  {
    name: "Arjun Deshmukh",
    role: "CAD Designer, Tata Advanced Systems",
    content:
      "CATIA V5 training from AeroSpark is best-in-class. The projects mirror real aerospace design challenges — I was productive from day one at my new role.",
    avatar: "/avatars/arjun.jpg",
    rating: 5,
  },
];
