import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
  try {
    const data = await req.json();
    const { name, email, phone, company, service, message } = data;

    if (!name || !email || !service || !message) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      console.error('Missing EMAIL_USER or EMAIL_PASS in environment variables');
      return NextResponse.json(
        { error: 'Server misconfiguration' },
        { status: 500 }
      );
    }

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const htmlContent = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #1a1a1a;">
        <h2 style="color: #00008B; border-bottom: 2px solid #eaeaea; padding-bottom: 10px;">New Consultation Request</h2>
        <div style="margin-top: 20px;">
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Phone:</strong> ${phone || 'Not provided'}</p>
          <p><strong>Company:</strong> ${company || 'Not provided'}</p>
          <p><strong>Service Required:</strong> ${service}</p>
        </div>
        <div style="margin-top: 30px;">
          <h3 style="color: #333;">Project Details:</h3>
          <div style="background-color: #f8f9fa; border-left: 4px solid #00008B; padding: 15px; border-radius: 4px; white-space: pre-wrap;">${message}</div>
        </div>
        <p style="margin-top: 40px; font-size: 12px; color: #666;">This email was automatically generated by the AeroSpark website.</p>
      </div>
    `;

    await transporter.sendMail({
      from: `"${name} (via AeroSpark)" <${process.env.EMAIL_USER}>`,
      to: 'asutoshashok89@gmail.com',
      replyTo: email,
      subject: `New Consultation Request: ${service} from ${name}`,
      html: htmlContent,
    });

    return NextResponse.json(
      { success: true, message: 'Email sent successfully' },
      { status: 200 }
    );
  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    );
  }
}
